enyo.depends(
	"SpeedTest.js",
	"BlankTest.js",
	"PanelTest.js",
	"DispatchTest.js",
	"InheritanceTest.js",
	"ListScrollingTest.js",
	"MoonListScrollingTest.js",
	"DataGridListScrollingTest.js",
	"DataListScrollingTest.js",
	"MoonEmptyPanelRenderTest.js",
	"MoonComplexPanelRenderTest.js",
	"MoonEmptyPanelAnimationForward.js",
	"MoonEmptyPanelAnimationBackward.js",
	"MoonComplexPanelAnimationForward.js",
	"MoonComplexPanelAnimationBackward.js",
	"DrawerTest.js"
);
