enyo.depends(
	"SpeedTest.js",
	"BlankTest.js",
	"PanelTest.js",
	"DispatchTest.js",
	"InheritanceTest.js",
	"ListScrollingTest.js",
	"MoonListScrollingTest.js",
	"MoonEmptyPanelRenderTest.js",
	"MoonComplexPanelRenderTest.js",
	"MoonEmptyPanelAnimationForward.js",
	"MoonEmptyPanelAnimationBackward.js",
	"MoonComplexPanelAnimationForward.js",
	"MoonComplexPanelAnimationBackward.js"
);
